### ISSUE TITLE
Improve metric intiialization to 0

### ISSUE THREAD

**Issue by mwitkow** [mwitkow/go-grpc-prometheus#5]
@brian-brazil in #2 mentioned:

> > As I said above: sadly it's not possible this is not possible from a technical point of view.
> They could be initialised on every RPC. If we can't do that then we need to create a success and failure metric without labels, which will avoid the main pitfalls (with the downside of loss of granularity).

gRPC interceptors only see an RPC when it lands, they have no access to all registrations. 

@brian-brazil, can you please clarify what you mean there? A single non-labeled metric? How will that help? What kind of pitfalls?

**Comment by brian-brazil** [comment]
We can't do anything about not knowing the different services, but once we intercept an rpc we know that that it exists and can initialise all labels then.

**Comment by mwitkow** [comment]
What are the possible problems?

**Comment by brian-brazil** [comment]
The issue with that approach is performance, as you've to initialise all the labels each time. A small cache would probably handle it.

**Comment by mwitkow** [comment]
I meant: what are the issues that uninitialized `labels` can cause? Are they related to division? Can you provide examples?

In case of the examples the `started_total` will always "exist" - because they're hit the first time time the interceptor sees the `grpc_service`+`grpc_method` combo.

**Comment by brian-brazil** [comment]
This issue is anytime you write an expression that presumes that labels always exist, but they don't

Your "unary request error percentage" example will return nothing if there has never been a failure.

**Comment by mwitkow** [comment]
Um. Ok, that's not that much of an issue.

**Comment by brian-brazil** [comment]
It can be quite a major issue, preventing alerts from firing depending exactly on how expressions are constructed. It's also really annoying to work with.

If the expression was written the other way around for example, a 100% error ratio would not trigger an alert.

**Comment by mwitkow** [comment]
Well there's not much that can be done here:
the gRPC service map of all services is [private](https://github.com/grpc/grpc-go/blob/master/server.go#L211) and not accessible from the Interceptor. Moreover, the `RegisterService` method is also public just so that generated code can use it. The `ServiceDesc` of the generated code is, handily, [private as well](https://github.com/grpc/grpc-go/blob/master/examples/helloworld/helloworld/helloworld.pb.go#L121)

Since most of the useful functions depend on `started_total` and that guarantees to have all the labels that any other metric will have, I see no reason to complicate the code with some manual pre-population.

**Comment by brian-brazil** [comment]
I'm not talking about the services, I'm talking about the `code` label on `grpc_server_handled_total`. 

Not pre-populating the codes means that only experts will be able to reliably graph or alert on failure rates.

**Comment by mwitkow** [comment]
You cannot pre-populate `grpc_code` since `grpc_server_handled_total` has `grpc_service` and `grpc_method` labels. Are you suggesting populating `grpc_service=dummy`? That's bad.

I will not complicate the per-request path with a pre-population of all error codes. This would require a cache lookup, which would need to be synchronized across requests.

If you feel like there are problems with discoverability of potential "fixed" values of labels, please add support for this in Prometheus itself by exposing label metadata (and metric metadata) in the server. I'm quite sure that many other people will encounter this problem. Just off the top of my head: http methods, http status codes etc.

**Comment by brian-brazil** [comment]
> You cannot pre-populate grpc_code since grpc_server_handled_total has grpc_service and grpc_method labels. Are you suggesting populating grpc_service=dummy? That's bad.

I'm proposing that once we know a `grpc_service` and `grpc_method` label that we populate the code label for them.  `grpc_service=dummy` wouldn't work in the general case.

> If you feel like there are problems with discoverability of potential "fixed" values of labels, please add support for this in Prometheus itself by exposing label metadata (and metric metadata) in the server.

Our solution is to handle this in the client.

**Comment by mwitkow** [comment]
Brian, please read my response. Causing locking or excessive map lookups for an undefined benefit of discoverability (there are docs) is not the way forward.

Please reconsider adding label metadata fi you believe that is a big problem. Otherwise, you can't expect third party open source contributors to jump through hoops.

**Comment by brian-brazil** [comment]
The problem here is that gRPC doesn't expose sufficient information to provide reliable metrics, so we have to do the next best thing.

If you want a better way to do things, I'd suggest filing a feature request with gRPC to get access to the list of services and methods.

> Causing locking or excessive map lookups for an undefined benefit of discoverability

The problem is not discovery, it is correctness. I've not mentioned label value discovery so I'm not sure where you got that from.

There are real failure modes. For example a 100% error ratio would result in an alert on the successful request ratio being too low never firing, leaving the user blind to the 100% failure ratio.

I've seen this type of problem myself many times, and postmortems mentioning this are not unknown.
The problem is that the failure mode is subtle. Everything seems to work fine until it doesn't, and the time it doesn't work is often during a nasty outage.

> Please reconsider adding label metadata fi you believe that is a big problem. Otherwise, you can't expect third party open source contributors to jump through hoops.

I don't think plumbing this through to Prometheus is an appropriate solution. This is a client side problem, we're unlikely to add complexity to Prometheus, the exposition formats and all client libraries to save maybe one line of code in the standard case.

The cache lookup would be a similar cost to `WithLabelValues` (around 70ns), to which there's already at least 4 calls to for each stream.
(One reason direct instrumentation is better is that we can usually avoid all these concurrent map lookup costs by taking pointers at initialisation).

> Just off the top of my head: http methods, http status codes etc.

This is unfortunately only a minor implementation detail of the challenges around HTTP.

**Comment by mwitkow** [comment]
@brian-brazil, the fact of the matter is: gRPC exposes a decent interface, good enough for other integrations (statsd, logging, auth). The interface is similar to HTTP, which many people use.
If Prometheus requires more, it IMHO is a failure on Prometheus' side. 

Expecting a third-party integration library to jump through hoops on a "hot" request path is a desperate solution to a wider problem. 

Nevertheless, I raised https://github.com/grpc/grpc-go/issues/689, hoping to get the gRPC interface necessary to work around Prometheus issue. 

As this affects other systems (HTTP at least) and not only gRPC, let's move the discussion to
https://github.com/prometheus/prometheus/issues/1636 where it belongs.
